In [6]:
import pandas as pd
import altair as alt

# Cargar archivo CSV
lolla = pd.read_csv(r"/Base de datos Lollapalooza 1(Base de datos 1).csv", delimiter=",", encoding="utf-8", dtype= {"edicion": int})
lolla.head()

,edicion lolla,artista,genero musical 01,genero musical 02,genero musical 03,integrantes,nacionalidad,headliner,escenario,veces en lollapalooza
0,2011,The Killers,Rock alternativo,Post-punk revival,New wave,4.0,Estadounidense,Sí,Coca Cola Zero Stage,1.0
1,2011,Jane's Addiction,Rock,Hard Rock,Punk Rock,4.0,Estadounidense,Sí,Claro Stage,1.0
2,2011,Kanye West,Hip Hop,Rap,Pop,1.0,Estadounidense,Sí,Coca Cola Zero Stage,1.0
3,2011,Cypress Hill,Rap,Hip Hop,Rap Rock,4.0,Estadounidense,No,Claro Stage,1.0
4,2011,30 Secons To Mars,Rock,Rock alternativo,Metal progresivo,4.0,Estadounidense,No,Coca Cola Zero Stage,1.0

In [7]:
lolla.shape

(1053, 10)

In [8]:
lolla.columns

Index(['edicion lolla ', 'artista ', 'genero musical 01', 'genero musical 02',
       'genero musical 03', 'integrantes', 'nacionalidad', 'headliner',
       'escenario', 'veces en lollapalooza'],
      dtype='object')

In [9]:
lolla.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1053 entries, 0 to 1052
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   edicion lolla          1053 non-null   int64
 1   artista                1053 non-null   object
 2   genero musical 01      1051 non-null   object
 3   genero musical 02      959 non-null    object
 4   genero musical 03      697 non-null    object
 5   integrantes            1040 non-null   float64
 6   nacionalidad           1053 non-null   object
 7   headliner              1053 non-null   object
 8   escenario              1053 non-null   object
 9   veces en lollapalooza  1052 non-null   float64
dtypes: float64(2), int64(1), object(7)
memory usage: 82.4+ KB

In [10]:
lolla["artista "].head()

0          The Killers
1     Jane's Addiction
2           Kanye West
3         Cypress Hill
4    30 Secons To Mars
Name: artista , dtype: object

In [11]:
lolla['headliner'].head()

0    Sí
1    Sí
2    Sí
3    No
4    No
Name: headliner, dtype: object

In [12]:
lolla['nacionalidad'].head()

0    Estadounidense
1    Estadounidense
2    Estadounidense
3    Estadounidense
4    Estadounidense
Name: nacionalidad, dtype: object

In [15]:
lolla["artista "].value_counts()

artista
Pedro Piedra            4
Rubio                   4
Francisca Valenzuela    4
Red Bull Batalla        4
Lucybell                4
                       ..
The Flaming Lips        1
Sublime With Rome       1
Fatboy Slim             1
30 Secons To Mars       1
Kanye West              1
Name: count, Length: 884, dtype: int64

In [16]:
lolla["headliner"].value_counts()

headliner
No     970
Sí      78
No       4
SÍ       1
Name: count, dtype: int64

In [17]:
lolla['nacionalidad'].value_counts()

nacionalidad
Chilena                      395
Estadounidense               228
Británica                     76
Argentina                     53
Canadiense                    25
                            ...
Canadiense-Estadounidense      1
Británica-Australiana          1
Británica-Escocesa             1
Neozelandesa-Croata            1
Estadounidense-chilena         1
Name: count, Length: 71, dtype: int64

In [22]:
lolla.columns = lolla.columns.str.strip()
lolla['headliner'] = lolla['headliner'].str.strip()
lolla['nacionalidad'] = lolla['nacionalidad'].str.strip()

In [23]:
lolla_headliners = lolla[lolla['headliner'] == 'Sí'].copy()

In [24]:
alt.Chart(lolla_headliners).mark_bar().encode(
    x=alt.X('count():Q', title='Cantidad de Headliners'),
    y=alt.Y('nacionalidad:N', sort='-x', title='País'),
    color=alt.Color('nacionalidad:N', legend=None),
    tooltip=['nacionalidad', 'count()']
).properties(
    title='Diversidad de Nacionalidades en Headliners',
    width=500
)

alt.Chart(...)